### ISSUE TITLE
Distributor widget GTM events tracking stoped workiing

### ISSUE THREAD

**Issue by RUjmiak** [MewsSystems/public#23]
Yesterday (25.6.) I found error in console after Mews Booking system is loaded which (I suppose) cause stop sending events to datalayer.  

You can find more details here - https://screencast.com/t/TzQ1wZVxnd5

Our GA events now - https://screencast.com/t/xv7Oe2M1vvi

Thanks

**Comment by jakubtkadlecek** [comment]
@RUjmiak booking engine experienced some issues during day of 25th. We corrected problem during subsequent engine updates. Can you please verify your event tracking is working correctly?

Thank you for pointing out errors in console. We will take care of them with regularly scheduled upgrades of booking engine.

**Comment by pbambusek** [comment]
Fixed.

Changelog: https://mewssystems.github.io/public/content/developers/distributor/widget/changelog.html#26052017

**Comment by fickomat** [comment]
@pbambusek We still have a problem with distributor events not working in checkout and confirmation.
First four events works fine after the update.
Analytics Events and Checkout Event should be fired here.

![image](https://cloud.githubusercontent.com/assets/15713916/26676870/d61345c8-46c9-11e7-890b-a335af52de5e.png)

Here is our overall setup
![image](https://cloud.githubusercontent.com/assets/15713916/26676960/20a6f5c6-46ca-11e7-874f-9ef463d1844c.png)

and analytics events tag setup
![image](https://cloud.githubusercontent.com/assets/15713916/26677003/51b90032-46ca-11e7-80b4-529b24195c80.png)

**Comment by pbambusek** [comment]
@matusficko Thanks for pointing out, we missed that initialization after eredirect to Merchant. It has been fixed with yesterday hotfix deploy.

Changelog:
https://mewssystems.github.io/public/content/developers/distributor/widget/changelog.html

**Comment by RUjmiak** [comment]
@pbambusek thanks this was our second problem :)

**Comment by matusficko** [comment]
Thank you for quick fix!
